chore: update dependencies, enhance ESLint configuration, and improve pre-commit hook
Signed-off-by: Rid <rid@cylo.io>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,6 @@
 #!/usr/bin/env sh
 echo "Running linting checks before commit..."
-# pnpm run lint:fix
-# if [ $? -ne 0 ]; then
-#   echo "Linting failed! Fix the errors before committing."
-#   exit 1
-# fi 
+if ! pnpm run lint:fix; then
+  echo "Linting failed! Fix the errors before committing."
+  exit 1
+fi 
